# index:
#    path: /
#    controller: App\Controller\DefaultController::index

menu:
    path : /
    controller : App\Controller\SensorsController::list

update :
    path : /update/{name}
    controller : App\Controller\SensorsController::display

newSensor :
    path  : /newSensor
    controller : App\Controller\SensorsController::AddSensor

newroom :
    path : /newRoom
    controller : App\Controller\RoomController::AddRoom

newcategory :
    path : /newCategory
    controller : App\Controller\CategoryController::AddCategory

delete :
    path : /deleteSensor/{id}
    controller : App\Controller\SensorsController::DeleteSensor