# index:
#    path: /
#    controller: App\Controller\DefaultController::index

menu:
    path : /
    controller : App\Controller\Filter::list

update :
    path : /update/{name}
    controller : App\Controller\Update::display

newSensor :
    path  : /newSensor
    controller : App\Controller\newSensor::AddSensor

newroom :
    path : /newRoom
    controller : App\Controller\newRoom::AddRoom

newcategory :
    path : /newCategory
    controller : App\Controller\newCategory::AddCategory

delete :
    path : /deleteSensor/{id}
    controller : App\Controller\Delete::DeleteSensor