# index:
#    path: /
#    controller: App\Controller\DefaultController::index

category:
    path : /menu
    controller : App\Controller\Filter::list

update :
    path : /update/{name}
    controller : App\Controller\Update::display
